# Generated by Django 5.2.5 on 2025-08-13 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegistration',
            new_name='UserSignup',
        ),
    ]
